# Generated by Django 4.1.5 on 2023-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
